[package]
name = "yaml_compare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
openapiv3 = "2.0.0"
serde_yaml = "0.9.27"
skim = "0.10.4"
